#!/bin/bash

function test()
{
   if [[ $1 -eq 0 ]]
   then
      echo -e "\x1B[1;32m✓ $2\x1B[0m"
   else
      echo -e "\x1B[1;31m✗ $2\x1B[0m"
   fi
}

[ "$(TZ=UTC+03:15 node -e 'd3 = require("./"); console.log(d3.timeHour.floor(new Date(1456279843199)))')" = "Tue Feb 23 2016 22:00:00 GMT-0315 (UTC)" ]; test $? "timeHour.floor with -:15 UTC offset"
[ "$(TZ=UTC+03:15 node -e 'd3 = require("./"); console.log(d3.timeHour.ceil(new Date(1456279843199)))')" = "Tue Feb 23 2016 23:00:00 GMT-0315 (UTC)" ]; test $? "timeHour.ceil with -:15 UTC offset"
[ "$(TZ=UTC+03:15 node -e 'd3 = require("./"); console.log(d3.timeHour.range(new Date(2011, 10, 7, 0), new Date(2011, 10, 7, 3)).join(","))')" = "Mon Nov 07 2011 00:00:00 GMT-0315 (UTC),Mon Nov 07 2011 01:00:00 GMT-0315 (UTC),Mon Nov 07 2011 02:00:00 GMT-0315 (UTC)" ]; test $? "timeHour.range with -:15 UTC offset"
[ "$(TZ=UTC-03:15 node -e 'd3 = require("./"); console.log(d3.timeHour.floor(new Date(1456279843199)))')" = "Wed Feb 24 2016 05:00:00 GMT+0315 (UTC)" ]; test $? "timeHour.floor with +:15 UTC offset"
[ "$(TZ=UTC-03:15 node -e 'd3 = require("./"); console.log(d3.timeHour.ceil(new Date(1456279843199)))')" = "Wed Feb 24 2016 06:00:00 GMT+0315 (UTC)" ]; test $? "timeHour.ceil with +:15 UTC offset"
[ "$(TZ=UTC-03:15 node -e 'd3 = require("./"); console.log(d3.timeHour.range(new Date(2011, 10, 7, 0), new Date(2011, 10, 7, 3)).join(","))')" = "Mon Nov 07 2011 00:00:00 GMT+0315 (UTC),Mon Nov 07 2011 01:00:00 GMT+0315 (UTC),Mon Nov 07 2011 02:00:00 GMT+0315 (UTC)" ]; test $? "timeHour.range with +:30 UTC offset"
[ "$(TZ=Asia/Kolkata node -e 'd3 = require("./"); console.log(d3.timeHour.floor(new Date(1456279843199)))')" = "Wed Feb 24 2016 07:00:00 GMT+0530 (IST)" ]; test $? "timeHour.floor with +:30 UTC offset"
[ "$(TZ=Asia/Kolkata node -e 'd3 = require("./"); console.log(d3.timeHour.ceil(new Date(1456279843199)))')" = "Wed Feb 24 2016 08:00:00 GMT+0530 (IST)" ]; test $? "timeHour.ceil with +:30 UTC offset"
[ "$(TZ=Asia/Kolkata node -e 'd3 = require("./"); console.log(d3.timeHour.range(new Date(2011, 10, 7, 0), new Date(2011, 10, 7, 3)).join(","))')" = "Mon Nov 07 2011 00:00:00 GMT+0530 (IST),Mon Nov 07 2011 01:00:00 GMT+0530 (IST),Mon Nov 07 2011 02:00:00 GMT+0530 (IST)" ]; test $? "timeHour.range with +:30 UTC offset"
[ "$(TZ=Asia/Kathmandu node -e 'd3 = require("./"); console.log(d3.timeHour.floor(new Date(1456279843199)))')" = "Wed Feb 24 2016 07:00:00 GMT+0545 (NPT)" ]; test $? "timeHour.floor with +:45 UTC offset"
[ "$(TZ=Asia/Kathmandu node -e 'd3 = require("./"); console.log(d3.timeHour.ceil(new Date(1456279843199)))')" = "Wed Feb 24 2016 08:00:00 GMT+0545 (NPT)" ]; test $? "timeHour.ceil with +:45 UTC offset"
[ "$(TZ=Asia/Kathmandu node -e 'd3 = require("./"); console.log(d3.timeHour.range(new Date(2011, 10, 7, 0), new Date(2011, 10, 7, 3)).join(","))')" = "Mon Nov 07 2011 00:00:00 GMT+0545 (NPT),Mon Nov 07 2011 01:00:00 GMT+0545 (NPT),Mon Nov 07 2011 02:00:00 GMT+0545 (NPT)" ]; test $? "timeHour.range with +:45 UTC offset"
[ "$(TZ=America/Sao_Paulo node -e 'd3 = require("./"); console.log(d3.timeDay.floor(new Date(Date.UTC(2016, 1, 21, 1))))')" = "Sat Feb 20 2016 00:00:00 GMT-0200 (BRST)" ]; test $? "timeDay.floor when daylight saving ends at midnight"
[ "$(TZ=America/Sao_Paulo node -e 'd3 = require("./"); console.log(d3.timeDay.floor(new Date(Date.UTC(2016, 1, 21, 2))))')" = "Sat Feb 20 2016 00:00:00 GMT-0200 (BRST)" ]; test $? "timeDay.floor when daylight saving ends at midnight"
[ "$(TZ=America/Sao_Paulo node -e 'd3 = require("./"); console.log(d3.timeDay.floor(new Date(Date.UTC(2016, 1, 21, 3))))')" = "Sun Feb 21 2016 00:00:00 GMT-0300 (BRT)" ]; test $? "timeDay.floor when daylight saving ends at midnight"
[ "$(TZ=America/Sao_Paulo node -e 'd3 = require("./"); console.log(d3.timeDay.floor(new Date(Date.UTC(2016, 1, 21, 4))))')" = "Sun Feb 21 2016 00:00:00 GMT-0300 (BRT)" ]; test $? "timeDay.floor when daylight saving ends at midnight"
[ "$(TZ=America/Sao_Paulo node -e 'd3 = require("./"); console.log(d3.timeDay.ceil(new Date(Date.UTC(2016, 1, 21, 1))))')" = "Sun Feb 21 2016 00:00:00 GMT-0300 (BRT)" ]; test $? "timeDay.ceil when daylight saving ends at midnight"
[ "$(TZ=America/Sao_Paulo node -e 'd3 = require("./"); console.log(d3.timeDay.ceil(new Date(Date.UTC(2016, 1, 21, 2))))')" = "Sun Feb 21 2016 00:00:00 GMT-0300 (BRT)" ]; test $? "timeDay.ceil when daylight saving ends at midnight"
[ "$(TZ=America/Sao_Paulo node -e 'd3 = require("./"); console.log(d3.timeDay.ceil(new Date(Date.UTC(2016, 1, 21, 3))))')" = "Sun Feb 21 2016 00:00:00 GMT-0300 (BRT)" ]; test $? "timeDay.ceil when daylight saving ends at midnight"
[ "$(TZ=America/Sao_Paulo node -e 'd3 = require("./"); console.log(d3.timeDay.ceil(new Date(Date.UTC(2016, 1, 21, 4))))')" = "Mon Feb 22 2016 00:00:00 GMT-0300 (BRT)" ]; test $? "timeDay.ceil when daylight saving ends at midnight"
[ "$(TZ=America/Sao_Paulo node -e 'd3 = require("./"); console.log(d3.timeDay.round(new Date(Date.UTC(2016, 1, 20, 14))))')" = "Sat Feb 20 2016 00:00:00 GMT-0200 (BRST)" ]; test $? "timeDay.round when daylight saving ends at midnight"
[ "$(TZ=America/Sao_Paulo node -e 'd3 = require("./"); console.log(d3.timeDay.round(new Date(Date.UTC(2016, 1, 20, 15))))')" = "Sun Feb 21 2016 00:00:00 GMT-0300 (BRT)" ]; test $? "timeDay.round when daylight saving ends at midnight"
[ "$(TZ=America/Sao_Paulo node -e 'd3 = require("./"); console.log(d3.timeDay.round(new Date(Date.UTC(2016, 1, 21, 14))))')" = "Sun Feb 21 2016 00:00:00 GMT-0300 (BRT)" ]; test $? "timeDay.round when daylight saving ends at midnight"
[ "$(TZ=America/Sao_Paulo node -e 'd3 = require("./"); console.log(d3.timeDay.round(new Date(Date.UTC(2016, 1, 21, 15))))')" = "Mon Feb 22 2016 00:00:00 GMT-0300 (BRT)" ]; test $? "timeDay.round when daylight saving ends at midnight"
[ "$(TZ=America/Sao_Paulo node -e 'd3 = require("./"); console.log(d3.timeDay.range(new Date(2016, 1, 19), new Date(2016, 1, 23)).join(","))')" = "Fri Feb 19 2016 00:00:00 GMT-0200 (BRST),Sat Feb 20 2016 00:00:00 GMT-0200 (BRST),Sun Feb 21 2016 00:00:00 GMT-0300 (BRT),Mon Feb 22 2016 00:00:00 GMT-0300 (BRT)" ]; test $? "timeDay.range when daylight saving ends at midnight"
[ "$(TZ=America/Sao_Paulo node -e 'd3 = require("./"); console.log(d3.timeDay.floor(new Date(Date.UTC(2016, 9, 16, 1))))')" = "Sat Oct 15 2016 00:00:00 GMT-0300 (BRT)" ]; test $? "timeDay.floor when daylight saving begins at midnight"
[ "$(TZ=America/Sao_Paulo node -e 'd3 = require("./"); console.log(d3.timeDay.floor(new Date(Date.UTC(2016, 9, 16, 2))))')" = "Sat Oct 15 2016 00:00:00 GMT-0300 (BRT)" ]; test $? "timeDay.floor when daylight saving begins at midnight"
[ "$(TZ=America/Sao_Paulo node -e 'd3 = require("./"); console.log(d3.timeDay.floor(new Date(Date.UTC(2016, 9, 16, 3))))')" = "Sun Oct 16 2016 01:00:00 GMT-0200 (BRST)" ]; test $? "timeDay.floor when daylight saving begins at midnight"
[ "$(TZ=America/Sao_Paulo node -e 'd3 = require("./"); console.log(d3.timeDay.floor(new Date(Date.UTC(2016, 9, 16, 4))))')" = "Sun Oct 16 2016 01:00:00 GMT-0200 (BRST)" ]; test $? "timeDay.floor when daylight saving begins at midnight"
[ "$(TZ=America/Sao_Paulo node -e 'd3 = require("./"); console.log(d3.timeDay.ceil(new Date(Date.UTC(2016, 9, 16, 1))))')" = "Sun Oct 16 2016 01:00:00 GMT-0200 (BRST)" ]; test $? "timeDay.ceil when daylight saving begins at midnight"
[ "$(TZ=America/Sao_Paulo node -e 'd3 = require("./"); console.log(d3.timeDay.ceil(new Date(Date.UTC(2016, 9, 16, 2))))')" = "Sun Oct 16 2016 01:00:00 GMT-0200 (BRST)" ]; test $? "timeDay.ceil when daylight saving begins at midnight"
[ "$(TZ=America/Sao_Paulo node -e 'd3 = require("./"); console.log(d3.timeDay.ceil(new Date(Date.UTC(2016, 9, 16, 3))))')" = "Sun Oct 16 2016 01:00:00 GMT-0200 (BRST)" ]; test $? "timeDay.ceil when daylight saving begins at midnight"
[ "$(TZ=America/Sao_Paulo node -e 'd3 = require("./"); console.log(d3.timeDay.ceil(new Date(Date.UTC(2016, 9, 16, 4))))')" = "Mon Oct 17 2016 00:00:00 GMT-0200 (BRST)" ]; test $? "timeDay.ceil when daylight saving begins at midnight"
[ "$(TZ=America/Sao_Paulo node -e 'd3 = require("./"); console.log(d3.timeDay.round(new Date(Date.UTC(2016, 9, 15, 14))))')" = "Sat Oct 15 2016 00:00:00 GMT-0300 (BRT)" ]; test $? "timeDay.round when daylight saving begins at midnight"
[ "$(TZ=America/Sao_Paulo node -e 'd3 = require("./"); console.log(d3.timeDay.round(new Date(Date.UTC(2016, 9, 15, 15))))')" = "Sun Oct 16 2016 01:00:00 GMT-0200 (BRST)" ]; test $? "timeDay.round when daylight saving begins at midnight"
[ "$(TZ=America/Sao_Paulo node -e 'd3 = require("./"); console.log(d3.timeDay.round(new Date(Date.UTC(2016, 9, 16, 14))))')" = "Sun Oct 16 2016 01:00:00 GMT-0200 (BRST)" ]; test $? "timeDay.round when daylight saving begins at midnight"
[ "$(TZ=America/Sao_Paulo node -e 'd3 = require("./"); console.log(d3.timeDay.round(new Date(Date.UTC(2016, 9, 16, 15))))')" = "Mon Oct 17 2016 00:00:00 GMT-0200 (BRST)" ]; test $? "timeDay.round when daylight saving begins at midnight"
[ "$(TZ=America/Sao_Paulo node -e 'd3 = require("./"); console.log(d3.timeDay.range(new Date(2016, 9, 14), new Date(2016, 9, 18)).join(","))')" = "Fri Oct 14 2016 00:00:00 GMT-0300 (BRT),Sat Oct 15 2016 00:00:00 GMT-0300 (BRT),Sun Oct 16 2016 01:00:00 GMT-0200 (BRST),Mon Oct 17 2016 00:00:00 GMT-0200 (BRST)" ]; test $? "timeDay.range when daylight saving begins at midnight"
